/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASkeletonButton: typeof import('ant-design-vue/es')['SkeletonButton']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Button: typeof import('./src/components/Button.vue')['default']
    CButton: typeof import('./src/components/CButton.vue')['default']
    CCardWhiteBoard: typeof import('./src/components/CCardWhiteBoard.vue')['default']
    CDynamicIcon: typeof import('./src/components/CDynamicIcon.vue')['default']
    CInput: typeof import('./src/components/Form/CInput.vue')['default']
    CSidebar: typeof import('./src/components/Layouts/CSidebar.vue')['default']
    DefaultLayout: typeof import('./src/components/Layouts/DefaultLayout.vue')['default']
    Excalidraw: typeof import('./src/components/Excalidraw.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layouts/Sidebar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
